image: maxking/mailman-ci-runner

django-1.8:
  script:
  - tox -e py27-django18

django-1.9:
  script:
  - tox -e py27-django19

django-1.10:
  script:
  - tox -e py27-django110

pep8:
  script:
  - tox -e pep8

django-latest:
  script:
  - tox -e py27-django-latest
  allow_failure: true
